#!/usr/bin/env python3
#
# i.e.
# cal Google Calendar https://calendar.google.com/calendar/u/0/r/week
#
import os
import sys
import re

homedir = os.path.expanduser("~")
LINK_PATH=f"{homedir}/.vim/sugavim/config/links"

with open(LINK_PATH, 'r') as file:
    lines = [x.strip() for x in file.readlines()]

if(len(sys.argv) < 2):
    print('you need to specify an argument.')
    sys.exit()

args = sys.argv[1:]
key  = args[0]

alias = {}
for line in lines:
    lsp = line.split(' ')
    key = lsp[0]
    url = lsp[-1]
    description = lsp[1:-1]
    alias[key] = (url, ' '.join(description))

def show_links(alias):
    for key, url_description in alias.items():
        url, description = url_description

        print(f"[{key}] {url[0:20]} | {description}")

if('-h' in args):
    show_links(alias)
else:
    url, description = alias[key]
    print(url)
    os.system(f"open {url}")
