#!/usr/bin/env python3
#
# inserter
#
#
# https://docs.microsoft.com/en-us/windows/win32/controls/about-rich-edit-controls

import sys
import os.path
from os import path
from pathlib import Path
import random

args = [x for x in sys.argv if x != "o"]

links = os.environ['HOME'] + '/.links'

def get_url(args):
    urls = list(filter(lambda x: x.startswith('http'), args))
    if(len(urls) == 0):
        print('url missing.')
        sys.exit()
    return urls[0]

def read(file):
    f = open(file, 'r')
    contents = f.read()
    f.close()
    return contents
    
if('l' in args):
    content = read(links)
    print(content)
    sys.exit()

if('r' in args):
    content = read(links)
    url = get_url(args)
    content = content.replace(url, '')
    f = open(links, 'a')
    f.write(content)
    f.close()
    sys.exit()

if(len(args) < 2):
    urls = list(filter(lambda x: x.startswith('http'), read(links).split('\n')))
    url_size = len(urls)
    idx = random.randint(0, url_size - 1)
    app = 'w3m '
    if(len(sys.argv) > 1 and sys.argv[1] == 'o'):
        app = 'open '
    print(app)
    os.system(app + urls[idx])
    sys.exit()

url = [x for x in args if x.startswith('http')][0]

contents = ''

if(path.exists(links)):
    contents = read(links)
else:
    Path(links).touch()

if(url in contents):
    sys.exit()

f = open(links, 'a')
f.write(url + '\n')
f.close()
