#!/usr/bin/env python3

import inflection
import sys

if(len(sys.argv) < 2):
    sys.exit()

for arg in sys.argv[1:]:
    arg = arg.replace('(', '') \
             .replace(')', '') \
             .replace(' ', '_') \
             .replace('-', '') \
             .replace(':', '') \
             .replace(';', '') \
             .replace('.', '')

    print(inflection.camelize(arg, False))
